data = {
    1 : "The protagonist, who has been living almost anonymously in St. Petersburg for eight years, feels an acute loneliness as the city empties for the summer. He wanders the streets, observing familiar faces and houses, feeling a connection to the city despite his isolation. One night, he encounters a woman crying by the canal. They strike up a conversation, and he learns her name is Nastenka. They share a moment of connection, and despite his social awkwardness and her initial hesitance, they form an immediate bond over their shared sense of loneliness and longing. Nastenka, playful and forthcoming, intrigues him with her lively spirit. They agree to meet again, setting the stage for a deeper exploration of their newfound relationship.",
    2 : "The narrative continues on the second night where the protagonist recounts a pleasant meeting with Nastenka, a young woman he recently met by the canal. They bond over their shared loneliness and dreams. Nastenka shares her backstory, involving her strict grandmother who limits her freedom, symbolized by pinning Nastenka's dress to hers. Despite this, Nastenka is vibrant and full of life, contrasting with the protagonist’s introspective solitude. They agree to meet again, deepening the protagonist's newfound feelings of connection and anticipation",
    3 : "In the third segment, Nastenka reveals her background and current emotional turmoil. She shares the story of her life with her controlling grandmother, who limits her freedom to the extent of physically pinning her dress to hers to keep her close. Despite this, Nastenka finds some relief when a young man, a new lodger, moves into their building. This lodger becomes a figure of fascination and hope for Nastenka, offering her books and moments of escape through trips to the theater.As Nastenka grows fond of the lodger, her emotional dependence deepens, culminating in his departure for Moscow with a promise to return for her if he can establish himself. His return to St. Petersburg brings no contact, leaving Nastenka in a state of despair and uncertainty about his feelings. She recounts this to the protagonist of the story, who suggests writing a letter to confront the lodger about his intentions, offering to help draft and deliver this crucial message.",
    4 : "On the third rainy night, the protagonist's hopes begin to waver. Nastenka reveals her anxieties about a man she loves who is supposed to return to her. Throughout the evening, it becomes clear that her heart belongs to another, causing a mix of emotions in the protagonist. As they share these moments, the protagonist's feelings deepen, but so does his realization of their unlikelihood. The night is a poignant mix of connection and underlying sadness, as Nastenka is preoccupied with another's return",
    5 : "The fourth night brings heartbreak and revelation. Nastenka is distraught over not receiving a response from the man she loves. In a moment of emotional vulnerability, the protagonist confesses his love to Nastenka. Although touched, Nastenka is fixated on the other man. As they part ways, her former lover appears, and she quickly returns to him, leaving the protagonist alone and reflecting on the fleeting moments of happiness they shared",
    6 : "The story concludes with a somber morning where the protagonist receives a letter from Nastenka explaining her marriage to her original love and asking for his forgiveness and friendship. Despite the pain, the protagonist treasures the brief happiness he experienced. The narrative ends with him accepting his solitude, enriched yet still tinged with melancholy from the bittersweet memories of Nastenka",
}

